version: "3.0"

services:

  mysql:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_process
      MYSQL_USER: user_one
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    platform: linux/x86_64

  php-fpm:
    build: docker/php-fpm
    user: $USER_ID:$GROUP_ID
    volumes:
      - ./:/app
    links:
      - mysql

  nginx:
    image: nginx:stable
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "85:80"
    links:
      - php-fpm